name: Build

on:
  pull_request:
  push:
    tags:
      - '**'

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Matterhook.NET.MatterhookClient.sln'

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # To make GitVersion work (installed as dependency in project)
    -
      name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    -
      name: Restore dependencies
      run: nuget restore $SOLUTION
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    -
      name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    -
      name: Run Tests
      run: dotnet test --no-restore --verbosity normal
    -
      name: Publish
      if: github.event_name != 'pull_request'
      run: |
        if [ "${{ secrets.NUGET_API_KEY }}" != "" ]; then
          echo "Pushing to nuget.org"
          nuget push Matterhook.NET.MatterhookClient/bin/Release/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
        else
          echo "Not pushing to nuget.org, no NUGET_API_KEY set in repo secrets"
        fi
        echo "Pushing to github packages"
        nuget push Matterhook.NET.MatterhookClient/bin/Release/*.nupkg -Source 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json' -ApiKey ${{secrets.GITHUB_TOKEN}}