name: Build

on:
  pull_request:
  push:
    tags:
      - '**'

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Matterhook.NET.MatterhookClient.sln'

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # To make GitVersion work (installed as dependency in project)
    -
      name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    -
      name: Restore dependencies
      run: nuget restore $SOLUTION
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    -
      name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
    -
      name: Publish
      if: github.event_name != 'pull_request'
      run: nuget push Matterhook.NET.MatterhookClient/bin/Release/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}